[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "zero-wam"
version = "0.0.0"
description = "Zero-WAM: In-Context World-Action Modeling from Human Videos"
authors = [
    { name = "Zero-WAM Authors" }
]
license = { file = "LICENSE.txt" }
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "torch==2.9.0",
    "torchvision==0.24.0",
    "diffusers==0.36.0",
    "transformers==4.55.2",
    "tokenizers>=0.21.4",
    "accelerate",
    "einops",
    "safetensors",
    "huggingface_hub",
    "tqdm",
    "imageio[ffmpeg]",
    "easydict",
    "numpy>=1.26.4,<2",
    "Pillow",
    "PyYAML",
    "websockets",
    "msgpack",
    "ftfy",
]

[project.optional-dependencies]
npu = ["torch-npu==2.9.0", "decorator==5.3.1", "attrs>=23.0", "absl-py"]
cuda = ["flash-attn"]
train = [
    "lerobot==0.3.3",
    "scipy",
    "wandb",
]
dev = [
    "pytest",
    "black",
    "flake8",
    "isort",
    "mypy",
    "huggingface-hub[cli]"
]

[project.urls]
homepage = "https://robbyant-research.github.io/Zero-WAM/"
documentation = "https://robbyant-research.github.io/Zero-WAM/"
repository = "https://github.com/robbyant-research/Zero-WAM"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
wan_va = ["assets/*.pt", "assets/norm_stats/*.json"]

[tool.setuptools.packages.find]
include = ["wan_va*"]

[tool.black]
line-length = 88

[tool.isort]
profile = "black"

[tool.mypy]
strict = true
